// Gera um esqueleto do banco da Tecnoar a partir de src/tipos/supabase.ts
// (gerado do banco real): enums e tabelas do schema public, mais o mínimo do
// Supabase (auth, storage, net, privado, papéis) para a migração do SOS rodar.
import fs from 'node:fs'

// Copiado do banco real: select table_name, column_name, generation_expression
// from information_schema.columns where table_schema = 'public' and is_generated <> 'NEVER'.
const GERADAS = {
  'clientes.documento_digitos': "regexp_replace(coalesce(documento, ''), '\\D', '', 'g')",
  'fornecedores.documento_digitos': "regexp_replace(coalesce(documento, ''), '\\D', '', 'g')",
  'vendedores.documento_digitos': "regexp_replace(coalesce(documento, ''), '\\D', '', 'g')",
  'veiculos.placa_normalizada': "upper(regexp_replace(placa, '[^A-Za-z0-9]', '', 'g'))",
  'os_produtos.valor_total': 'round(greatest(quantidade * valor_unitario - desconto, 0), 2)',
  'os_servicos.valor_total': 'round(greatest(quantidade * valor_unitario - desconto, 0), 2)',
}

export function gerarEsqueleto(caminhoTipos) {
  const s = fs.readFileSync(caminhoTipos, 'utf8')
  const inicioPublic = s.indexOf('  public: {')
  const pub = s.slice(inicioPublic)

  // ── enums
  const enums = {}
  const blocoEnums = pub.slice(pub.indexOf('    Enums: {'), pub.indexOf('    CompositeTypes: {'))
  const reEnum = /\n      (\w+):((?:\s*\|?\s*"[^"]*")+)/g
  let m
  while ((m = reEnum.exec(blocoEnums))) enums[m[1]] = [...m[2].matchAll(/"([^"]*)"/g)].map((x) => x[1])

  // ── tabelas (só Row)
  const blocoTabelas = pub.slice(pub.indexOf('    Tables: {'), pub.indexOf('    Views: {'))
  const tabelas = {}
  const reTab = /\n      (\w+): \{\n        Row: \{\n([\s\S]*?)\n        \}/g
  while ((m = reTab.exec(blocoTabelas))) {
    const corpo = m[2]
    const cols = []
    const reCol = /\n?\s{10}(\w+)\??:\s*([\s\S]*?)(?=\n\s{10}\w+\??:|$)/g
    let c
    while ((c = reCol.exec(corpo))) cols.push([c[1], c[2].replace(/\s+/g, ' ').trim()])
    tabelas[m[1]] = cols
  }

  const sqlEnums = Object.entries(enums)
    .map(([n, vs]) => `create type public.${n} as enum (${vs.map((v) => `'${v}'`).join(', ')});`)
    .join('\n')

  function tipoSql(nome, tipo, tabela) {
    const nulo = /\|\s*null/.test(tipo)
    const base = tipo.replace(/\|\s*null/g, '').trim()
    const enumM = base.match(/Database\["public"\]\["Enums"\]\["(\w+)"\](\[\])?/)
    if (enumM) return `public.${enumM[1]}${enumM[2] ? '[]' : ''}`
    if (base === 'boolean') return 'boolean'
    if (base === 'Json') return 'jsonb'
    if (base === 'string[]') return 'text[]'
    if (base === 'number[]') return 'numeric[]'
    if (base === 'number') {
      if (nome === 'id') return 'bigint'
      if (/^(numero|codigo|ordem|prioridade|km|km_atual|versao_atual|km_inicial|km_limite)$/.test(nome)) return 'integer'
      return 'numeric'
    }
    if (base === 'string' && (process.env.COLUNAS_TEXTO ?? '').split(',').includes(nome)) return 'text'
    if (base === 'string') {
      if (nome === 'id' || /_id$/.test(nome) || /_por$/.test(nome) || nome === 'singleton_id') return 'uuid'
      if (/(_em|_at)$/.test(nome)) return 'timestamptz'
      return 'text'
    }
    void nulo
    void tabela
    return 'text'
  }

  const sqlTabelas = Object.entries(tabelas)
    .map(([t, cols]) => {
      const defs = cols.map(([n, tipo]) => {
        let sql = `${n} ${tipoSql(n, tipo, t)}`
        const ts = tipoSql(n, tipo, t)
        // Colunas geradas do banco real (information_schema): gravar nelas dá erro lá, e aqui também.
        const gerada = GERADAS[`${t}.${n}`]
        if (gerada) return `${sql} generated always as (${gerada}) stored`
        if (n === 'id' && ts === 'uuid') sql += ' primary key default gen_random_uuid()'
        else if (n === 'id' && ts === 'bigint') sql += ' generated by default as identity primary key'
        else if (n === 'singleton' && ts === 'boolean') sql += cols.some(([x]) => x === 'id') ? ' unique default true' : ' primary key default true'
        else if (/^(created_at|updated_at)$/.test(n)) sql += ' default now()'
        else if (n === 'situacao' && /situacao_registro|situacao_usuario|situacao_item/.test(tipo)) sql += " default 'ativo'"
        else if (n === 'aprovacao') sql += " default 'pendente'"
        else if (n === 'estado' && /estado_produto_os/.test(tipo)) sql += " default 'necessario'"
        else if (n === 'codigo' && ts === 'integer') sql += ' generated by default as identity'
        else if (n === 'numero' && ts === 'integer') sql += ' generated by default as identity'
        else if (ts === 'boolean') sql += ' default false'
        else if (n === 'quantidade') sql += ' default 1'
        else if (/^(valor_unitario|desconto|valor_total)$/.test(n)) sql += ' default 0'
        else if (n === 'ordem') sql += ' default 0'
        return sql
      })
      return `create table public.${t} (\n  ${defs.join(',\n  ')}\n);`
    })
    .join('\n\n')

  const supabaseMinimo = `
create extension if not exists pgcrypto;
create schema if not exists extensions;
create schema if not exists auth;
create schema if not exists storage;
create schema if not exists net;
create schema if not exists privado;
do $$ begin create role anon; exception when duplicate_object then null; end $$;
do $$ begin create role authenticated; exception when duplicate_object then null; end $$;
do $$ begin create role service_role; exception when duplicate_object then null; end $$;
grant usage on schema public, auth, storage, extensions to anon, authenticated, service_role;

create table auth.users (
  id uuid primary key default gen_random_uuid(),
  email text,
  raw_user_meta_data jsonb default '{}'::jsonb,
  last_sign_in_at timestamptz,
  confirmation_sent_at timestamptz,
  email_confirmed_at timestamptz
);
create function auth.uid() returns uuid language sql stable as $f$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid
$f$;
grant execute on function auth.uid() to anon, authenticated, service_role;
grant select on auth.users to authenticated, anon;

create table storage.buckets (id text primary key, name text, public boolean, file_size_limit bigint);
create table storage.objects (id uuid primary key default gen_random_uuid(), bucket_id text, name text);
alter table storage.objects enable row level security;
create function storage.foldername(name text) returns text[] language sql immutable as $f$
  select (string_to_array(name, '/'))[1:array_length(string_to_array(name, '/'), 1) - 1]
$f$;

create table net.chamadas (id bigint generated always as identity, url text, headers jsonb, body jsonb);
create function net.http_post(url text, headers jsonb default '{}', body jsonb default '{}') returns bigint language sql as $f$
  insert into net.chamadas (url, headers, body) values (url, headers, body) returning id
$f$;

create table privado.config (chave text primary key, valor text);
`

  const complementos = `
alter table public.recursos add constraint recursos_chave_unica unique (chave);
alter table public.notificacoes add constraint notificacoes_usuario_id_fkey foreign key (usuario_id) references public.usuarios(id);

-- Permissão real: admin tudo; senão, perfil ou permissão individual.
create function public.tem_permissao(p_recurso text, p_acao public.acao_permissao) returns boolean
language sql stable security definer set search_path = public as $f$
  select exists (
    select 1 from public.usuarios u
    where u.id = auth.uid() and u.situacao = 'ativo'
      and (u.is_admin
           or exists (select 1 from public.perfil_permissoes pp where pp.perfil_id = u.perfil_id and pp.recurso = p_recurso and pp.acao = p_acao)
           or exists (select 1 from public.usuario_permissoes up where up.usuario_id = u.id and up.recurso = p_recurso and up.acao = p_acao and up.concedida))
  )
$f$;
grant execute on function public.tem_permissao(text, public.acao_permissao) to authenticated, anon;

-- Supabase dá acesso de tabela aos papéis; quem filtra é a RLS.
grant select, insert, update, delete on all tables in schema public to authenticated;
grant select on all tables in schema public to anon;
alter default privileges in schema public grant select, insert, update, delete on tables to authenticated;
alter default privileges in schema public grant select on tables to anon;

-- Pior caso de propósito: RLS ligada e uma política antiga que libera tudo a
-- qualquer conta logada. A trava do SOS precisa segurar mesmo assim.
do $x$ declare t text; begin
  for t in select tablename from pg_tables where schemaname = 'public' loop
    execute format('alter table public.%I enable row level security', t);
    execute format('create policy legado_logado_le_tudo on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $x$;
`
  return { sql: supabaseMinimo + '\n' + sqlEnums + '\n\n' + sqlTabelas + '\n' + complementos, tabelas, enums }
}
