import { IDS } from './mock-sos.mjs'

/** Todas as telas do app SOS, por persona. Usado pela captura e pela varredura de responsividade. */
export const ROTAS = [
  { id: '01-publico-login', nome: 'Login', persona: 'anonimo', path: '/entrar' },
  { id: '01b-publico-login-mecanico', nome: 'Login do mecânico', persona: 'anonimo', path: '/mecanico/entrar' },
  { id: '02-publico-cadastro', nome: 'Cadastro', persona: 'anonimo', path: '/cadastro' },
  { id: '03-publico-recuperar-senha', nome: 'Recuperar senha', persona: 'anonimo', path: '/esqueci-senha' },
  { id: '04-publico-termos', nome: 'Termos de uso', persona: 'anonimo', path: '/termos' },
  { id: '05-publico-privacidade', nome: 'Privacidade', persona: 'anonimo', path: '/privacidade' },
  { id: '06-publico-conta-excluida', nome: 'Conta excluída', persona: 'anonimo', path: '/conta-excluida' },
  { id: '07-publico-acompanhamento', nome: 'Acompanhamento público', persona: 'anonimo', path: '/acompanhar/token-demo' },
  { id: '08-equipe-operacao', nome: 'Operação/equipe', persona: 'equipe', path: '/' },
  { id: '09-cliente-home-claro', nome: 'Cliente · Início claro', persona: 'cliente', path: '/', tema: 'claro' },
  { id: '09b-cliente-home-escuro', nome: 'Cliente · Início escuro', persona: 'cliente', path: '/', tema: 'escuro' },
  { id: '10-cliente-sos-localizacao-claro', nome: 'Cliente · SOS claro', persona: 'cliente', path: '/sos', delay: 1800, tema: 'claro' },
  { id: '10b-cliente-sos-localizacao-escuro', nome: 'Cliente · SOS escuro', persona: 'cliente', path: '/sos', delay: 1800, tema: 'escuro' },
  { id: '11-cliente-chamados', nome: 'Cliente · Chamados', persona: 'cliente', path: '/chamados' },
  { id: '12-cliente-chamado-detalhe', nome: 'Cliente · Chamado ao vivo', persona: 'cliente', path: `/chamado/${IDS.chamado}` },
  { id: '13-cliente-veiculos', nome: 'Cliente · Veículos', persona: 'cliente', path: '/veiculos' },
  { id: '14-cliente-historico', nome: 'Cliente · Histórico', persona: 'cliente', path: '/historico' },
  { id: '15-cliente-revisoes', nome: 'Cliente · Revisões', persona: 'cliente', path: '/revisoes' },
  { id: '16-cliente-contato', nome: 'Cliente · Contato', persona: 'cliente', path: '/contato' },
  { id: '17-cliente-tecno-ia', nome: 'Cliente · TECNO IA', persona: 'cliente', path: '/tecno-ia', delay: 1400 },
  { id: '18-cliente-notificacoes', nome: 'Cliente · Notificações', persona: 'cliente', path: '/notificacoes' },
  { id: '19-cliente-perfil', nome: 'Cliente · Perfil', persona: 'cliente', path: '/perfil' },
  { id: '20-mecanico-painel-claro', nome: 'Mecânico · Painel claro', persona: 'mecanico', path: '/', tema: 'claro' },
  { id: '20b-mecanico-painel-escuro', nome: 'Mecânico · Painel escuro', persona: 'mecanico', path: '/', tema: 'escuro' },
  { id: '21-mecanico-chamados', nome: 'Mecânico · Chamados', persona: 'mecanico', path: '/chamados' },
  { id: '22-mecanico-atendimento', nome: 'Mecânico · Atendimento', persona: 'mecanico', path: `/chamado/${IDS.chamado}` },
  { id: '23-mecanico-notificacoes', nome: 'Mecânico · Notificações', persona: 'mecanico', path: '/notificacoes' },
  { id: '24-mecanico-perfil-claro', nome: 'Mecânico · Perfil claro', persona: 'mecanico', path: '/perfil', tema: 'claro' },
  { id: '24b-mecanico-perfil-escuro', nome: 'Mecânico · Perfil escuro', persona: 'mecanico', path: '/perfil', tema: 'escuro' },
  { id: '25-mecanico-os-lista', nome: 'Mecânico · Minhas OS', persona: 'mecanico', path: '/os', tema: 'claro' },
  { id: '26-mecanico-os-detalhe', nome: 'Mecânico · OS', persona: 'mecanico', path: `/os/${IDS.os}`, tema: 'claro' },
  { id: '27-mecanico-os-nova', nome: 'Mecânico · Nova OS', persona: 'mecanico', path: '/os/nova', tema: 'claro' },
  { id: '28-mecanico-novo-chamado', nome: 'Mecânico · Novo chamado', persona: 'mecanico', path: '/novo-chamado', tema: 'claro' },
  { id: '29-mecanico-catalogo', nome: 'Mecânico · Produtos', persona: 'mecanico', path: '/catalogo/produtos', tema: 'claro' },
  { id: '29b-mecanico-servicos', nome: 'Mecânico · Serviços', persona: 'mecanico', path: '/catalogo/servicos', tema: 'claro' },
  { id: '30-mecanico-tecno-ia', nome: 'Mecânico · Tecno IA', persona: 'mecanico', path: '/tecno-ia', tema: 'claro' },
  { id: '31-mecanico-historico', nome: 'Mecânico · Histórico', persona: 'mecanico', path: '/historico', tema: 'claro' },
  { id: '03b-publico-nova-senha', nome: 'Nova senha', persona: 'anonimo', path: '/nova-senha' },
  { id: '12b-cliente-chamado-finalizado', nome: 'Cliente · Chamado finalizado', persona: 'cliente', path: `/chamado/${IDS.chamadoFinalizado}` },
  // Telas de dentro do atendimento (?tela=…), cada uma é uma tela inteira.
  ...['os', 'diagnostico', 'observacoes', 'fotos', 'produtos', 'servicos', 'orcamento', 'ia', 'finalizar'].map((t) => ({
    id: `22-mecanico-atendimento-${t}`,
    nome: `Mecânico · Atendimento · ${t}`,
    persona: 'mecanico',
    path: `/chamado/${IDS.chamado}?tela=${t}`,
    tema: 'claro',
  })),
]
